# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dab374ac0082ba77fe1a8475cd8880ff0c51938a5664d999d4c9a09e46c8c87b613d52c3133390c8fa4b35a789b0c934fc0962e4dd765bca2f788c7b6b9056d4

test:
  secret_key_base: b779fb0d90c68663ff5a68ade6513303ed21ed1c891d4e71f3f71a52ba6c9a4d41d320793146e4e029fd50bf2ea7136bca09d003a2b4708f65d6df00a5bc67f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
