# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d842b18564a8d9fb69aa6cebc92f84e4674e553555d738f50bde314db48d94add2c4098a8319e91e7cb708c72296cc16827baf25f847fdec268f5eaa180e5d95

test:
  secret_key_base: 66230ed8f94ed1f1c8b36d095f2fa593ce86c169ac9b7cfdeac7fb470411b3b67828c6e9abc46cc76a36067ed61ed1719185c0b6cc05fe62b2c9743830890b88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
